# Generated by Django 4.1.1 on 2022-09-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=100, verbose_name='To-Do task')),
                ('completed', models.BooleanField(default=False)),
                ('timeToComplete', models.TimeField()),
            ],
        ),
    ]
